from . import res_company
from . import res_config_settings
from . import product_template
from . import varnish_type
from . import stamping_option
from . import print_orientation
from . import material_type
from . import color_ink
from . import printing_cylinder
