{
    "name": "Rocafer Custom",
    "summary": "Customization for work-order",
    "version": "17.0.1.0.0",
    "category": "Products",
    "author": "Manuel Calero, Salvador Gonzalez, Abraham Carrasco, Xtendoo",
    "license": "LGPL-3",
    "application": True,
    "depends": [
        'product',
        'contacts',
        'stock',
        'mrp',
    ],
    "data": [
        'views/product_template_view.xml',
        'views/varnish_type_view.xml',
        'views/printing_cylinder_view.xml',
        'views/color_ink_view.xml',
        'views/stamping_option_view.xml',
        'views/print_orientation_view.xml',
        'views/material_type_view.xml',
        'views/res_confing_settings_view.xml',
        'data/rocafer_data.xml',
        'security/ir.model.access.csv',
    ],
    "installable": True,
}
